version: "3"
services:
    mongo:
        container_name: mongodb
        image: mongo
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_ID}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}